modLoader="javafml" 
loaderVersion="[1,)"
issueTrackerURL="https://github.com/noobanidus/Lootr/issues"
license="https://github.com/noobanidus/Lootr/blob/1.16/LICENSE"

[[mixins]]
config="lootr.mixins.json"

[[mods]] 
modId="lootr" 
version="${version}"
displayName="Lootr" 
displayURL="https://minecraft.curseforge.com/projects/lootr" 
authors="Noobanidus"
description='''
Makes loot chest loot per-user.
'''
[[dependencies.lootr]]
    modId="neoforge"
    mandatory=true 
    versionRange="[20.4-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lootr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,)"
    ordering="NONE"
    side="BOTH"
